$ANSIBLE_VAULT;1.1;AES256
66333931643466303463313362306134343135303031366132336266646133643235356636323832
6362306262323361396236626165306135313135323431620a643838313633623231333238666461
31613432336630616435343536393163386139653536633935636363323965363232313238373262
6666616266376332610a393739316539376135323761393233373465393666303939363434306633
61383436633133633732643863393862663535316439303337356234326363333334633233313930
32303862633637633639316465356663643237303565386539656239643138663333653162633163
62663161646563306366313666626137356264306431363064353332623163343433646363643736
66393433396531396438666435303838613963666533353738306134653835643637323337393731
62393963343135396637666233303431346461643031616331633065303434376231383933373932
66386237353666343863653835396136336131323634663534386262393161666531626531316334
35383738396161633230373064373430353236333964303561383863376430376138373238356564
61393734663434373964393431353938383565346435346431663533333030666166646261366264
3136
